# Copyright (c) 2020-2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: justice-adminportal-extension-website
  namespace: ${NAMESPACE}
spec:
  maxReplicas: ${MAX_REPLICAS}
  minReplicas: ${MIN_REPLICAS}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: justice-adminportal-extension-website
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: ${HPA_CPU_THRESHOLD}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: ${HPA_MEMORY_THRESHOLD}
