# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

FROM accelbyte/node:10.15.3-alpine-3.11

RUN apk update && \
    apk add yarn bash git openssh

RUN mkdir -p /root/.ssh; \
  ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts