# Copyright (c) 2020-2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager

{{- if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  {{- if .Values.canary.enabled }}
  name: {{ .Chart.Name }}-primary
  {{- else}}
  name: {{ .Chart.Name }}
  {{- end}}
  namespace: {{ .Values.namespace | default "dev" | quote }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- if .Values.canary.enabled }}
      app: {{ .Values.app }}-primary
      {{- else}}
      app: {{ .Values.app }}
      {{- end}}
      component: {{ .Values.component }}
      stage: {{ .Values.stage | default "dev" | quote }}
      tier: {{ .Values.tier }}
{{- end }}
