# Copyright (c) 2020-2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager

{{- if (eq (default "true" (.Values.service.enabled | toString)) "true") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace | default "dev" | quote }}
  labels:
    app: {{ .Values.app }}
    component: {{ .Values.component }}
    stage: {{ .Values.stage | default "dev" | quote }}
    tier: {{ .Values.tier }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort | default 8080 }}
      name: http
      protocol: TCP
  selector:
    app: {{ .Values.app }}
    component: {{ .Values.component }}
    stage: {{ .Values.stage | default "dev" | quote }}
    tier: {{ .Values.tier }}
{{- end }}
