# Copyright (c) 2020-2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager

{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace | default "dev" | quote }}
spec:
  gateways:
  - {{ .Values.canary.gatewayName | default "justice-gateway" | quote }}
  hosts:
  - {{ .Values.justice.domain }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.justice.path | default "/admin-extension" | quote }}
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
          number: {{ .Values.service.port }}
{{- end }}