# Copyright (c) 2019 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: <SERVICE_NAME>
  namespace: <K8S_NS>
  labels:
    app: <SERVICE_NAME>
spec:
  replicas: <REPLICAS>
  selector:
    matchLabels:
      app: <SERVICE_NAME>
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: <SERVICE_NAME>
        deployment_id: <DEPLOYMENT_ID>
    spec:
      containers:
        - name: justice-adminportal-extension-website
          image: <ADMINPORTAL_EXTENSION_WEBSITE_IMAGE>
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: justice-common-variables
            - configMapRef:
                name: justice-adminportal-extension-website-variables
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: <CPU_LIMIT>
              memory: <MEMORY_LIMIT>
            requests:
              cpu: <REQUEST_CPU>
              memory: <REQUEST_MEMORY>

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: <K8S_NS>
  name: <SERVICE_NAME>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <SERVICE_NAME>
  minReplicas: <MIN_REPLICAS>
  maxReplicas: <MAX_REPLICAS>
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
