apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: <SERVICE_NAME>
  namespace: <K8S_NS>
spec:
  targetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: <SERVICE_NAME>
  progressDeadlineSeconds: <CANARY_PROGRESS_DEADLINE_SECONDS>
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: <SERVICE_NAME>
  service:
    port: 80
    targetPort: 8080
    gateways:
      - <ISTIO_GATEWAY_NAME>.<K8S_NS>.svc.cluster.local
      - mesh
    hosts:
      - <ISTIO_GATEWAY_BASE_URL>
    match:
      - uri:
          prefix: /admin-extension/
  skipAnalysis: false
  canaryAnalysis:
    interval: <CANARY_ANALYSIS_INTERVAL>
    threshold: <CANARY_ANALYSIS_FAILURE_THRESHOLD>
    maxWeight: <CANARY_ANALYSIS_MAX_WEIGHT>
    stepWeight: <CANARY_ANALYSIS_STEP_WEIGHT>
    metrics:
      - name: request-success-rate
        threshold: <CANARY_REQUEST_SUCCESS_RATE_THRESHOLD>
        interval: <CANARY_REQUEST_SUCCESS_RATE_INTERVAL>
      - name: request-duration
        threshold: <CANARY_REQUEST_DURATION_THRESHOLD>
        interval: <CANARY_REQUEST_DURATION_INTERVAL>